### ISSUE TITLE
Easy-to-find, easy-to-read list of included controller mappings

### ISSUE THREAD

**Issue by ronso0** [mixxxdj/website#254]
"is this and that controller supported in Mixxx x.y??"
this comes up frequently in the forums or (even in github wtf https://github.com/mixxxdj/mixxx/pull/4326)

Reason for this is probably that ['Supported Devices'](https://mixxx.org/features/#hardware) links to an overwhelming wiki page [mixxx/wiki/Hardware-Compatibility](https://github.com/mixxxdj/mixxx/wiki/Hardware-Compatibility) with way too much, badly accessible information considering the rather simple question "is my controller supported?"
Also, once you found the mapping table (not sorted a-z), the distinction between Cerfified / Community Supported Mappings is confusing IMO.

Let's merge those two tables and put them in a better place on the website
-- or simply link to [manual > controllers](https://manual.mixxx.org/2.3/en/hardware/manuals.html#controllers)
The most info of the Hardware Compatibility page is covered by
https://manual.mixxx.org/2.3/en/chapters/introduction.html
https://manual.mixxx.org/2.3/en/chapters/hardware.html

**Comment by Be-ing** [comment]
Had already been addressed in #118...

**Comment by Swiftb0y** [comment]
fyi I just added a quick sentence as a dirty fix to page on the wiki: https://github.com/mixxxdj/mixxx/wiki/Hardware-Compatibility/_compare/f6dc761cbf2d7e4e00e498bcda6ad14dc87601cf

**Comment by ronso0** [comment]
unfortunately that doesn't eliminate the root cause that users need to click an scroll way to much.
I propose to simply link to https://manual.mixxx.org/2.3/en/hardware/manuals.html#controllers

> Had already been addressed in #118...

which appears (at first glance) to have stalled for the same reason many PRs have: too many controversial changes at once, bike-shedding, hardened fronts...

and doesn't solve the issue because it still links to that unhandy wiki page.

**Comment by Be-ing** [comment]
> and doesn't solve the issue because it still links to that unhandy wiki page.

Which was current a year ago and the manual still has not replaced it due to missing images of controllers.

**Comment by Swiftb0y** [comment]
> unfortunately that doesn't eliminate the root cause that users need to click an scroll way to much.
I propose to simply link to https://manual.mixxx.org/2.3/en/hardware/manuals.html#controllers

I agree, I still wanted to add the disclaimer so the people that found on that page some other way know that the table is outdated and they should look in the manual instead.

**Comment by ronso0** [comment]
> > and doesn't solve the issue because it still links to that unhandy wiki page.
> 
> Which was current a year ago and the manual still has not replaced it due to missing images of controllers.

not all controllers have photos, true.
but photos are irrelevant for a quick lookup if my controller is supported IMO. users know how the desired controller looks like.
though we should migrate existing photos from the wiki to the manual. I doubt this makes a difference, in case there are copyright concerns (actually it's free ad for controllers).

**Comment by Holzhaus** [comment]
IMHO the hardware compatibility wiki page should simply be removed or made a link to the manual. Personally, I stopped looking at the wiki at all. The vast majority of information is outdated or outright wrong.

**Comment by ronso0** [comment]
okay, the link is in place.
To make the wiki page obsolete I'd add a `See also: supported controllers` note to https://manual.mixxx.org/2.3/en/chapters/hardware.html#controllers
Any objections?

**Comment by Holzhaus** [comment]
> okay, the link is in place.
> To make the wiki page obsolete I'd add a `See also: supported controllers` note to https://manual.mixxx.org/2.3/en/chapters/hardware.html#controllers
> Any objections?

No objections, but such a link is already present the free text. Maybe we can avoid duplication somehow? Not sure how tho.

**Comment by Be-ing** [comment]
This is still not easy to find on the website. There should be a link to the list in the navigation menu.

**Comment by Be-ing** [comment]
Also the linked manual page has many significant regressions from the wiki. There are no prices, nor any indication whether the devices are commercially available or discontinued, nor info about whether they have an integrated audio interface, still no pictures...

**Comment by ronso0** [comment]
This was a first step forward.

Are prices really relevant? they differ from country to country, also the vary over time (decrease because of new, better controllers, or --for excellent and/or durable controllers-- increase due to high 2nd hand demand).
When I was looking for a supported a few years back, I went through the list and checked every controller online. I didn't really care about the prices listed in the wiki because due to limited budget I was lookin for 2nd hand devices anyway.

Sure 'integrated audio interface' was helpful. IMO we could migrate a stripped list to the manual and use that instead of the plain link list.

**Comment by ronso0** [comment]
small steps:
* Discover > About
* migrate stripped controller overview?
* add link to supported controllers to the navbar?

**Comment by ronso0** [comment]
> No objections, but such a link is already present the free text. Maybe we can avoid duplication somehow?

True, but the first two paragraphs are a more general introduction to controllers so I only skimmed through the third one, and I didn't spot it right away. So maybe the situation can be improved ; )

**Comment by Be-ing** [comment]
> Are prices really relevant?

Yes. It doesn't do someone with a $250 budget any good to have to sort through a list of devices that includes $1000+ controllers.

**Comment by Be-ing** [comment]
> True, but the first two paragraphs are a more general introduction to controllers so I only skimmed through the third one, and I didn't spot it right away. So maybe the situation can be improved ; )

The list should have prominent explanations that support can be added for new controllers and the technical requirements for that (USB class compliant). Otherwise people may think they are stuck with the list of already supported controllers.

**Comment by ronso0** [comment]
well, then we can try to migrate that, too.

Looking at https://github.com/mixxxdj/mixxx/wiki/Hardware-Compatibility#mixxx-certified-mappings
I'd remove
* **Balanced Outputs** that should be clarified in the respective manual
* **Supported since Mixxx version** who cares?

That would already make the table more compact.

**Comment by ronso0** [comment]
> > Are prices really relevant?
> 
> Yes. It doesn't do someone with a $250 budget any good to have to sort through a list of devices that includes $1000+ controllers.

I think the **Description** column (or Category?) is equally helpful, no?
But if the table can be designed handy _with_ the Price colmn I don't object to include it.

**Comment by Be-ing** [comment]
> Supported since Mixxx version who cares?

That is a general indication of how old the mapping as a hint that old mappings may be woefully incomplete or badly designed. We could replace it with an explicit indication of legacy/reviewed. It is also helpful as an indicator of which mappings need updating.

**Comment by ronso0** [comment]
> That is a general indication of how old the mapping as a hint that old mappings may be woefully incomplete or badly designed

Maybe for devs, sure. But I doubt new users looking for a controller would read that column that way.

**Comment by Holzhaus** [comment]
If the controller has an integrated audio interface, then the manual page should have an audio setup section that explains how to configure the audio interface in Mixxx anyway (which channel is main, which one is headphones, etc).

Regarding prices: The manual is not a shopping guide. The manual is for finding out if your controller you already have (or are planning to buy) is supported and how it works. 

When I checked the page, a lot of prices were outdated, and some controllers were even discontinued. It's extremely maintenance heavy to keep it up to date. I dont think it's worth to keep that page in the current form. 

If you feel we should have a shopping guide, I'd propose a different kind instead: just a wiki page that recommends one controller per price category (entry level, midrange, expensive) that we feel has okayish build quality and a relatively fully-featured mapping.

**Comment by Holzhaus** [comment]
But tbh, I dont think we really need that. Everyone can just google some random "the 10 best dj controllers", keep the list from the manual open in anothet tab, then check if the controller you're interested in is supported.

**Comment by ronso0** [comment]
also I recall users simply asking "which controller would you recommend? I have this and that in mind, and my budget is ..."

**Comment by Be-ing** [comment]
> If you feel we should have a shopping guide, I'd propose a different kind instead: just a wiki page that recommends one controller per price category (entry level, midrange, expensive) that we feel has okayish build quality and a relatively fully-featured mapping.

I don't think we should only endorse one specific product. We could maintain a short list of currently commercially available devices with reviewed mappings for a few price ranges (maybe  <= $300, $300 - $750, > $750).
